<#
.SYNOPSIS
Fills a topic with large messages, so `backend/kafka/tests/fetch_budget.rs`
can measure what a fetch actually costs on the kind of topic that made the
Data tab unusable: multi-megabyte JSON, spread over several partitions.

.DESCRIPTION
Assumes a broker is already running — `scripts/e2e-compression-fixtures.ps1`
starts one if you need it. Records are generated by Kafka's own
producer-perf-test rather than the console producer, which cannot send a
record larger than a line of stdin.

Both the topic and the producer need their size limits raised: the broker
rejects anything over `max.message.bytes` (1 MB by default) and the producer
over `max.request.size`.

.EXAMPLE
pwsh scripts/e2e-large-message-fixtures.ps1
$env:KAFKAOXIDE_E2E_BOOTSTRAP = "localhost:9092"
cargo test -p kafkaoxide-kafka --test fetch_budget -- --nocapture
#>
[CmdletBinding()]
param(
    # Short on purpose — see the note in e2e-compression-fixtures.ps1 about
    # Kafka's .bat launchers overrunning cmd.exe's command-line limit.
    [string]$KafkaHome = "C:\kt",
    [string]$Bootstrap = "localhost:9092",
    [string]$Topic = "big-2mb",
    [int]$Partitions = 4,
    [int]$Records = 120,
    [int]$RecordBytes = 2097152
)

$ErrorActionPreference = "Stop"
$bin = Join-Path $KafkaHome "k\bin\windows"
# Headroom over the record size for the batch framing around it.
$limit = $RecordBytes + 8 * 1024 * 1024

& "$bin\kafka-topics.bat" --bootstrap-server $Bootstrap --create --topic $Topic `
    --partitions $Partitions --replication-factor 1 --if-not-exists `
    --config "max.message.bytes=$limit" | Out-Null

& "$bin\kafka-producer-perf-test.bat" --topic $Topic --num-records $Records `
    --record-size $RecordBytes --throughput -1 `
    --producer-props "bootstrap.servers=$Bootstrap" "max.request.size=$limit" `
    "buffer.memory=$($limit * 4)" "batch.size=$RecordBytes" | Select-Object -Last 1

Write-Host "`n$Records x $([math]::Round($RecordBytes / 1MB, 1)) MB records in $Topic across $Partitions partitions."
Write-Host "Now run:"
Write-Host "  `$env:KAFKAOXIDE_E2E_BOOTSTRAP = `"$Bootstrap`""
Write-Host "  cargo test -p kafkaoxide-kafka --test fetch_budget -- --nocapture"
